title: Kakuly
theme: minima

# 公式ドキュメント準拠の書き方
minima:
  skin: dark

# RSSフィードをオフにする
feed:
  path: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: "Music Producer" # 下側のKakulyがこの文字に変わります
description: "Portfolio" # サイトの説明文になります
