title: Kakuly
theme: minima

# ここは念のため残す
minima:
  skin: dark

# WiFiマークを消すために、feedをあえて入れない
plugins:
  - jekyll-seo-tag

author: "Music Producer" # 下側のKakulyがこの文字に変わります
description: "Portfolio" # サイトの説明文になります
