name: Update Works from YouTube

on:
  push:
    paths:
      - 'update_works.py'
      - 'known_works.json'  # JSONの直接編集時にも発動
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 書き込み権限を明示
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests google-generativeai

      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python update_works.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add works.md known_works.json
          
          # 変更がある場合のみコミット
          if ! git diff --cached --exit-code --quiet; then
            git commit -m "Auto update works.md and cache"
            git pull --rebase origin main
            git push origin main
          fi
